### ISSUE TITLE
Music/Media pauses or stops when Kaku first opens

### ISSUE THREAD

**Issue by SpongebobSquamirez** [0xbad1d3a5/Kaku#17]
Apps like DoubleTwist will pause when Kaku opens, and apps like TuneIn Radio will stop streaming and need to be rebuffered before they start again. Don't remember the effects on VLC Media Player, but all media stops in some form on all apps.

**Comment by 0xbad1d3a5** [comment]
What version of Kaku are you on? I am almost certain this should be fixed by #11.

**Comment by SpongebobSquamirez** [comment]
It wasn't fixed last night, but I guess I didn't check again after updating. It seems to be fixed now. Hurray!
